# Generated by Django 3.0.5 on 2020-07-10 22:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(choices=[('open', 'Abierto'), ('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='open', max_length=59)),
                ('monto_total', models.FloatField(default=0, verbose_name='Monto total')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(default=datetime.datetime.now)),
                ('fm', models.DateTimeField(default=datetime.datetime.now)),
                ('Nombre', models.CharField(help_text='Nombre de la categoria', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(default=datetime.datetime.now)),
                ('fm', models.DateTimeField(default=datetime.datetime.now)),
                ('nombre', models.CharField(default='Marca', max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(default=datetime.datetime.now)),
                ('fm', models.DateTimeField(default=datetime.datetime.now)),
                ('Nombre', models.CharField(help_text='Nombre de la categoria', max_length=50)),
                ('Um', models.CharField(choices=[('0', 'Kilogramos'), ('1', 'Litros'), ('2', 'Unidades')], max_length=1, verbose_name='unidad de medida')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Productos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('fc', models.DateTimeField(default=datetime.datetime.now)),
                ('fm', models.DateTimeField(default=datetime.datetime.now)),
                ('Nombre', models.CharField(help_text='Nombre de producto', max_length=40)),
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('precio', models.FloatField(default=0)),
                ('descripcion', models.CharField(default='descripcion', help_text='Descripcion de productos', max_length=100)),
                ('color', models.CharField(blank=True, help_text='Color del producto', max_length=20, null=True)),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ferreteria')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Categoria')),
                ('TipoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.TipoProducto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
