# Generated by Django 3.0.5 on 2020-07-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='Um',
            field=models.CharField(choices=[('Kgs', 'Kilogramos'), ('Lts', 'Litros'), ('Un', 'Unidades'), ('mm', 'Milimetros'), ('Mts', 'Metros'), ('Cms', 'Centimetros')], max_length=15, verbose_name='unidad de medida'),
        ),
    ]
