# Generated by Django 3.0.5 on 2020-07-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20200710_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='Um',
            field=models.CharField(choices=[('Kgs', 'Kilogramos'), ('Lts', 'Litros'), ('Un', 'Unidades')], max_length=15, verbose_name='unidad de medida'),
        ),
    ]
