# Generated by Django 3.0.5 on 2020-06-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20200613_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Stock',
            new_name='stock',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='estatus',
            field=models.CharField(choices=[('open', 'Abierto'), ('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='open', max_length=59),
        ),
        migrations.AlterField(
            model_name='carritoproducto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
