# Generated by Django 3.0.8 on 2020-07-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_auto_20200625_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='monto_total',
            field=models.FloatField(default=0, verbose_name='Monto total'),
        ),
    ]
