# Generated by Django 3.0.5 on 2020-07-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0010_carrito_monto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ferreteria'),
        ),
    ]
