# Generated by Django 3.0.5 on 2020-07-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0011_auto_20200704_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoproducto',
            name='Descripcion',
        ),
    ]
