# Generated by Django 3.0.5 on 2020-07-09 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0012_remove_tipoproducto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fc',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fm',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='marca',
            name='fc',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='marca',
            name='fm',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fc',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fm',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fc',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fm',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
