# Generated by Django 2.2.10 on 2020-06-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200607_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.CharField(blank=True, choices=[('cliente', 'cliente'), ('proveedor', 'proveedor'), ('empleados', 'empleados'), ('ventas', 'ventas')], default='cliente', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
