# Generated by Django 3.0.6 on 2020-06-12 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("producto", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="id_proveedor",
            field=models.ForeignKey(
                limit_choices_to={"cargo": "Proveedor"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="carritoproducto",
            name="carrito",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="producto.Carrito",
            ),
        ),
        migrations.AddField(
            model_name="carritoproducto",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="producto.Producto"
            ),
        ),
        migrations.AddField(
            model_name="carrito",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tipoproducto", unique_together={("categoria", "Nombre")},
        ),
    ]
