# Generated by Django 2.2.10 on 2020-06-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producto", "0004_carrito_carritoproducto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipoproducto",
            name="Descripcion",
            field=models.CharField(
                help_text="Descripcion de la categoria", max_length=100
            ),
        ),
    ]
