# Generated by Django 2.2.10 on 2020-06-08 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producto", "0005_auto_20200608_0011"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="tipoproducto", unique_together=set(),),
    ]
