# Generated by Django 3.0.6 on 2020-06-14 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20200613_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='name',
            new_name='nombre',
        ),
    ]
