# Generated by Django 2.2.10 on 2020-06-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20200608_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoproducto',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
