# Generated by Django 2.2.10 on 2020-06-10 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producto", "0007_auto_20200608_0141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carritoproducto",
            name="cantidad",
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name="carritoproducto",
            name="carrito",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="producto.Carrito",
            ),
        ),
    ]
