# Generated by Django 3.0.5 on 2020-06-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.CharField(blank=True, choices=[('Proveedor', 'Proveedor'), ('Cliente', 'Cliente'), ('Empleado', 'Empleado'), ('Administrador', 'Administrador')], default='Cliente', max_length=254, null=True),
        ),
    ]
