# Generated by Django 3.0.5 on 2020-06-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200625_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
