# Generated by Django 3.0.5 on 2020-06-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200625_0533'),
    ]

    operations = [
    ]
