# Generated by Django 3.0.5 on 2020-06-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200625_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.CharField(blank=True, choices=[('Proveedor', 'Proveedor'), ('Cliente', 'Cliente'), ('Empleado', 'Empleado'), ('Administrador', 'Administrador'), ('Venta', 'Venta')], default='Cliente', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
