# Generated by Django 3.0.5 on 2020-07-11 02:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(default=datetime.datetime.now)),
                ('fm', models.DateTimeField(default=datetime.datetime.now)),
                ('direccion', models.CharField(blank=True, help_text='direccion', max_length=250, null=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('comuna', models.CharField(blank=True, help_text='comuna', max_length=100, null=True, verbose_name='Comuna')),
                ('tipo_documento', models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura')], default='BOLETA', max_length=15, null=True, verbose_name='Tipo documento')),
                ('tipo_despacho', models.CharField(choices=[('DOMICILIO', 'Domicilio'), ('TIENDA', 'Recojo en tienda')], default='TIENDA', max_length=15, null=True, verbose_name='Estado')),
                ('cli_nombres', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombres')),
                ('cli_apellidos', models.CharField(blank=True, max_length=250, null=True, verbose_name='Apellidos')),
                ('cli_rut', models.CharField(blank=True, max_length=250, null=True, verbose_name='Rut')),
                ('cli_empresa', models.CharField(blank=True, max_length=250, null=True, verbose_name='Empresa')),
                ('precio', models.IntegerField(default=0, verbose_name='Precio')),
                ('estado', models.CharField(choices=[('BORRADOR', 'BORRADOR'), ('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado')], default='BORRADOR', max_length=30, verbose_name='Estado')),
                ('carrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.Carrito')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
