# Generated by Django 3.0.6 on 2020-06-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producto", "0006_auto_20200613_2224"),
        ("cmp", "0002_ordencompra_carrito"),
    ]

    operations = [
        migrations.RenameModel(old_name="OrdenCompra", new_name="venta",),
    ]
