# Generated by Django 3.0.6 on 2020-06-16 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producto", "0006_auto_20200613_2224"),
        ("cmp", "0003_auto_20200616_1207"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="producto",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="producto.CarritoProducto",
            ),
            preserve_default=False,
        ),
    ]
