# Generated by Django 3.0.6 on 2020-06-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cmp", "0004_venta_producto"),
    ]

    operations = [
        migrations.RemoveField(model_name="venta", name="producto",),
    ]
