# Generated by Django 3.0.8 on 2020-07-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0005_remove_venta_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cli_apellidos',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cli_nombres',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cli_rut',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Rut'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_despacho',
            field=models.CharField(choices=[('DOMICILIO', 'Domicilio'), ('TIENDA', 'Recojo en tienda')], default='TIENDA', max_length=15, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='comuna',
            field=models.CharField(blank=True, help_text='comuna', max_length=100, null=True, verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='direccion',
            field=models.CharField(blank=True, help_text='direccion', max_length=250, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'BORRADOR'), ('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado')], default='BORRADOR', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='Precio'),
        ),
    ]
