# Generated by Django 3.0.5 on 2020-07-09 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0008_venta_cli_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fc',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fm',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
