# Generated by Django 3.0.5 on 2020-07-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(default=0, verbose_name='precio')),
                ('cantidad', models.FloatField(default=0, verbose_name='cantidad')),
                ('total', models.FloatField(default=0, verbose_name='total')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=45, verbose_name='Número')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo_documento', models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura')], default='BOLETA', max_length=15, verbose_name='Tipo documento')),
                ('tipo_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Credito')], default='CONTADO', max_length=15, verbose_name='Tipo pago')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('estado', models.CharField(choices=[('BORRADOR', 'BORRADOR'), ('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido')], default='BORRADOR', max_length=15, verbose_name='Estado')),
            ],
            options={
                'permissions': (('access_modulo_abastecimiento', '* Access modulo abastecimiento'), ('list_pedido', 'List pedido')),
            },
        ),
    ]
